version: '3'

services:
  web:
    restart: always
    build: .
    command: gunicorn annotater.wsgi:application --bind 0.0.0.0:81 --worker-tmp-dir /dev/shm --workers=2 --threads=4 --worker-class=gthread
    #command: python annotater/manage.py runserver 0.0.0.0:80
    #entrypoint: /bin/bash
    #stdin_open: true
    #tty: true

    expose:
      - 81
    env_file:
      - ./prod.env

networks:
  default:
    external:
      name: nginx-proxy
