# Generated by Django 3.1.13 on 2021-07-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('resolvable_object_id', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=800)),
                ('source', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
