# Generated by Django 3.1.13 on 2021-07-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
